hash-format = "sha256"

[[files]]
file = "mods/addonslib.pw.toml"
hash = "bd8e33f831b15d37e2c3b95837fcd27da49dcdbe57c74b0a8a2ce2bc5136a5b4"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "bf4133b4ac7b08983c98dcfb4cbfe4cc2b10698efb935d19378fd6a27490dd22"
metafile = true

[[files]]
file = "mods/alexs-mobs-naturalist-compat.pw.toml"
hash = "4582e0baac124b6ed5fa7117667b4e96bc9c1543763fa0235526bce6fcdc5181"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "e1016eb125a5a41a10f80847eb00affae0e539e703846f303949ed5d82b7f1bf"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "a5ebca2719b693273a637acf7c45c60f0e6a064775852e514b8328d8c94b98e8"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "064b0019e4f545599e5af2a4f74f11777086fce18e68f0b93dd77136ce7c0193"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "258431b158c3adc8e7bf4ac8ea9cec20def2e3c373294488d72c238bcbd7538a"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "354a23e95a756fa2e8110b4d93a58e97c83409c33cf683c27c495f51848f2f41"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "501acdaa439603e3a002cd2da5aad794ff9f39b2c75270bfab5779e2d7c6e0d8"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "262483c4f54a8171396664e16917c2d2f9145db7f9052fac99aebfb53b40e3cb"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "a45bbe1f9c5947251c59bb51adfb7493e4023d5728dab1e6b8f116fdf8bf896f"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "440a806e54d48cd4c5ef447ff8f1a6cd9a99d53d02ab90d50204be9b31c2f30d"
metafile = true

[[files]]
file = "mods/builders-delight.pw.toml"
hash = "dd3e909b4a5c69bf083e71beb203ec33b59ba9121280382bd7cd34dbbab45ee8"
metafile = true

[[files]]
file = "mods/c2mef.pw.toml"
hash = "92f000167f0c5665fa6f4a351889a58db7235ed8ebdb086a21a28a7024d347ad"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "457f82eb5d7b278e706d1c544ffb4186b6e8d45ff69f6af03d92e9c2758b8a94"
metafile = true

[[files]]
file = "mods/cc-vs.pw.toml"
hash = "773e0ff71b5370216cd1e6485be0d89aa63a153fb56a896e548f3c315c509d95"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "b0732421ae2999d558a7b70a11fa86a93738ca33f6f3ec343017796df9c47d9c"
metafile = true

[[files]]
file = "mods/chloride.pw.toml"
hash = "5fffcedde4d14f05b332a6a70680340ae2021d2697b45e49ffedb073abcb7c5c"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "0bdcf1c5057873c78db71bee196ccf5ec846f6cf82f639b094668b3ba92e151f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/cluttered.pw.toml"
hash = "27c3f5f7c3ec18f41738529c32ac522350e0e713d1ecc6293de2905e25731bfe"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "852ee3d5dea735c0c8f4c030edb06164863e7d27eef535c697f86a8b20a1cff0"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8cea6a7ec6b151f92a3a62261530bb1aefe173ad19840c0319aa10e0d8ab2386"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "b9f602d8ff484f7cae702fdfb45d006ed47e77efbdb0a552da2fa14132137dc8"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "6a07c5b47f1a9e875ea4fd35c9a76bd0abe44de50c1095b3ed985d47be5507cf"
metafile = true

[[files]]
file = "mods/create-clockwork.pw.toml"
hash = "d31c742e6dacf85d60415a75dbbe70e68ce17839ceeec858235f599606ab4632"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
hash = "e66368c5ad668587b094ef86ee48ee7d12fdc701c40da46fb1f1d31e400945a5"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "07bc61993957000b9c2ff6e1e5c0a4ef246aa18745f70a7a8c1c875b7b2bddd7"
metafile = true

[[files]]
file = "mods/create-ore-excavation.pw.toml"
hash = "880a30dbb8a40fcbe8fc808379bdf0d864a20b52150266001ed53bdabc44d040"
metafile = true

[[files]]
file = "mods/create-propulsion.pw.toml"
hash = "4abe8d2eab7c8e327597b05f600ef2dd1ab061ed86e5d72d7a496b3db6a9892b"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "ba16d5e568349bc79bb6a648090047fee23db3931f5399f9ad09c930410c740c"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
hash = "4f64bc81a381a3cb0c637829d547d8b0f5daa0ea29fe84a9e43a91784763745e"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "1eceb4e4ab86c793f992ce9444e92f46dae76c3f744d8e19feb1143fb6c01939"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "9eefd607e0d54ec444e798ccdeede1a09a3939440bd1e11c11b84c07a5134be2"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
hash = "dc23ac7c75b3f33b93f5725c9d6cfb2e62575550f2b8b01683397e35ad1a3955"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "c5ea75feae4d340856611f78a29e6f1f0b7e707bfe43847f11d25fac1769dee7"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "5ac6fe9a921d8fa00456ec2e18da02ede5c0da424c5c5b57da1206feeac40ff6"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7b32032b0892b53e1e5daf5410b78b4d98b7bdcbe2184f1d643098de36674865"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "4c5ec7476521092a74d8ae1b894e44903a3d7834898674294f0ce4ddb040b251"
metafile = true

[[files]]
file = "mods/explorations.pw.toml"
hash = "571128da9799a70c8b7c27d31a2c726291602fde9dad7749f78eee6227a68f3b"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "832e8a46a8abf0363eeeea3f860b6b8ec5af2e9e8bb717be03fee848470dd538"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "2a2f2168bf03bfa3034ad9583588676c5d66b6f7c767df9fe259ab55350792d2"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
hash = "91a06c75da039bec6407f291c12d61a2d492c7a43bfe0648b6f6f3e2bb66ee49"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "4fb9f19ebe3e65cf811ffcd807d5f1d1059b976195720f46bfd87420d94b102b"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "a3d9047f4cca960840f572b1a0ff3ef2cd881e0a1b5a6783ac0ce333097b99c9"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "79d8c527a416d0dfe54695701e13456580981084195ef4888bb1b61dcfa12e32"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "71f185e62d546881244d4b5a213ebc3d2d6df14b0218c0e5dd6426fcb22cb55f"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "12e6cb4e6f2a5c0342a7f61ece1f118d637e53e34b6691d53b36fed317022dfd"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "4fae5700ea63683044764c374f8651bb60c29e8bea465417d61998421724de5c"
metafile = true

[[files]]
file = "mods/hearth-and-home.pw.toml"
hash = "3d52663acb2436d6891c4f962a78ceaec929cf5a82bc38d41a863a168a6e065d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4bdf4efade5b9448d5257ef4c327e173bb0f37b9ac95b861340109016f4e2de2"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "3aa4d2e503b7a4544868954aa8175335ee34714a8b44cc2a41cdbb833e271c31"
metafile = true

[[files]]
file = "mods/immersiveengineering.pw.toml"
hash = "f0f53a142295b7d004100bea2cf0f60b06854b40eddc9abb8a447db4e57d4883"
metafile = true

[[files]]
file = "mods/jade-vs.pw.toml"
hash = "494a2284ce26be17d16b47ce940daffdd8f94d32bf337f39d902edf5b54086b3"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0fbcc8cf03336e6bed425e2115fc4ff1a3a05be5c655228b305e70380eb08b57"
metafile = true

[[files]]
file = "mods/jei-multiblocks.pw.toml"
hash = "c907dd6abbe34a94ed429f9caac9f02175cdc6df721ec95104216d45b6a97b02"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "50a5158efb2ae3a0fae74e75227cfc13703b9a231c5264e11cefc3b1aff7e5ba"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7ea985404ee4cc9082472c6869ec146309f526e395361b39f2f4c1a43506c41d"
metafile = true

[[files]]
file = "mods/lets-do-beachparty.pw.toml"
hash = "d78e971517d18ba6628d707e5a4a379e68499893ce17e92e490e945b3c60e115"
metafile = true

[[files]]
file = "mods/lets-do-herbalbrews.pw.toml"
hash = "b720172434e663a1e7d87e0b3b14c0fcbd0032bb14b4ed1885f5c4b32614994f"
metafile = true

[[files]]
file = "mods/lets-do-vinery.pw.toml"
hash = "94255c24694569e26337079e3ff81165b4e914ab427d4dab0e1d78b65325ba9f"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "ee387ba74c2c7e999d48071408abbd1ca322e70f36e79c590a150c9572d3a9cb"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "e4f414ece2ec81f6dd2dfb8c0176670a576b988f60c8b45a1f4b749b4d008c9d"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "c671e975aad1c5aeeb6ddd19894baa899334cc266001402c1a956f83c465cc34"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "1f258ed4b0c47751210d6bbb993b124aaebc692c726e8a93abb4fbbd1f1474ed"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
hash = "9abe732e3bc657c4123d4ccd482405dca9388539ee3bf3715b60ca74dbf01632"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "a205d0ab764efa4bb2eb93c114bbfde4cd3e117d117be9a941b8b56148945d0a"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "bd555889b27b5518a595b27838464e1af089c282873fde02ea50c75394edb25f"
metafile = true

[[files]]
file = "mods/macaws-quark.pw.toml"
hash = "566cf4cd7b8b82829a317e9efb2df27783990bdf62cc8ec948918ce3d0b51f24"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "1191b45155fb0f23f5a3fe4b9170b73f52a1c9599de504fe922e4ea7e7e3c95f"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "27745585e7d6cebb2fcb687563ce64d67a6dedc9ba1755b34d08309f591c8e92"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "40d34a4deede6848d6a49a9f1cf8fdd2af9dd1de058ffeb77e247099e087621f"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "8fb0ae9433533a1d24f9b738d6fa27f1d3091b10fd60fd9b0944b48901993c7e"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "adb67ada5c165ea4a43f4c3e53ffd61c90e21292596b5609d97e938f6e8e7b16"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ade41e4315735aa9116a0222b332e03d3f8df6eea301764d40d0bdc40f5e8689"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "ab170eabaeec3e80c59e850a7d8aee32edfffd6a1e40e2c2f44575c69d122054"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f7f82c3216ba9bfac7b9d040d0a1845d94f693b70f9981f5caf497e81f73bfae"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "6e751d439bd79d7ea28edd68c4bd75a13ed0696908a470b73699cd887a9080e2"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
hash = "6039fa77bfd0871c009092508bbaaed5f25947af425943fe3a2c8e6b32cd3102"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
hash = "8b3dc6fa116657eba16f3550bd6468ba4aab315c35952d1de7c2d165033b3a2d"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "4cd211200d17b109bb15f88c7b0c6ba29d9c0af6d2feb76fc7fe4eabff2e4ffe"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "55c6d0b8ee25fd6a37a964805de3d2eab3f20d73a88ba77a63b4a51fd985d9dd"
metafile = true

[[files]]
file = "mods/philips-ruins.pw.toml"
hash = "a5d901ff59798d05e6129aa77557489011ff09119a122708d15e0ba4123cce44"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "5b0f3ac0bb04d8a210680e33558fb4e3e0feccf20e12e0d12ab668f2bc67159e"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "4ab869d8784f4ac318b5c92fa3d9e65f997352b8b57f34b409ca6f171637f0fe"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "8df897c0f7831e919aa528c3c1e5239f39439c123d99761230ab2357132bad98"
metafile = true

[[files]]
file = "mods/rechiseled-chipped.pw.toml"
hash = "7dcd9a76d74b57f0fba9444a4320dd3105fad49ec46fc4b9ad4c0f3d250abcca"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "442f784b7c8e3d3231e407a9af4530c16fff9c301a5f57144fb5d895c754ded9"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "5c07edd0c8fe82e85efd6c027476ba54cf98291526803b74614c3436292e4ab6"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "7f38bb5c863c04b013a2c6ed75d799525ba3cc5a548279adde6e9329ff308dd4"
metafile = true

[[files]]
file = "mods/simple-hats.pw.toml"
hash = "d230becbad974464c274e76081ff460f4b66724ef7f590cfc8fe8ff9253f2c43"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "7451fffd4702db08b9d04aca87ec103c1694e2370bd8c7ced7e379a9f1e10816"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "fee227f06f4426c3de411320e7c736e503b169a145a6ed899430e9573848ef10"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "31111e9d3599390e45028fd416c7a0d407fb5821324c7682f9e2d828fce61b5a"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "40d2f59654c7b030249b141f36c6a9411018cb515fe16847078d30f7b15d6261"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "253233a2a1f20855f3a202857f4a7e5b6459326af30d39946467a142264999d8"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "0be4976227df8e261fd362889bf8e85b93e224d1b1c3cd2a11b73a9de3b64083"
metafile = true

[[files]]
file = "mods/sundries.pw.toml"
hash = "5f9fc501880c589e4874141a28c3df3fb879eb69a507b2a5de50be085bda7aa7"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "1cf9cb3955b075664ea4fba13b47fe7160975740a28864983aebd53d39c1946e"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "b969799c17defc1e7c76e4605557c9d32802a0004a5e45b7044e85d3d9c43345"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "1a7d83ff96739b35bfb9035ff23db0a95d30bceb1a018b078a2df96fcf09ab59"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "14117b94c456598c9acece143c7a0da3cf56d13182d035a74a2da8a52dd19cbd"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "6160cdcd8b686e90f72e76072ba96de7c5ae40460b3771401222ddebdee1d5ed"
metafile = true

[[files]]
file = "mods/travelers-titles.pw.toml"
hash = "16e2c84951ba32efac8703ccb7b36631b70cb514d402fa8fb4f89031f2a63a58"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "08a5b69474ddf223809a4e624f123dd3886362011663989c1bbacd6b5167baf0"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "559456029cff17724272b8307ea10e5745e4fcfa0991c6c9c9516a8b7fba6309"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "1a592e56f6720b44d1031d2d715d454eff2099e915160c0c75f853ae8b314b15"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "7e7b7624e041a1364971057d1c47f2b74730e191f142b73aa50223f95978dd96"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "152c6732da180e958fb29f492bae2e468d4dfd423ce4d3d0d31ef31c2eec6c61"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
hash = "c35cd5713162c90a988800682e017f90862027c3b2a98cd01de45a323d0ab6e6"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "532f07775974b695733981b2548859d3bc76c743781a5da5035d40fd6e485ab0"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "c35112cced2eec8e5782c5c4327ae31bce16cc1356c75e52000053e890e0f0c1"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "302d69d833264022aa7ff781dbcde7f60f3c9e3021881b29f6f59223c36579c8"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "8c8b596c0e8f7366e30ee6edbd591fba9ef16741c25a505e64de9a299cd72e80"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "41aa01e9d0507d3131eb5fd2f6d8f2b7c54237e30a94e2a3bf6f52915cb8a688"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "05f825a655bc94af6ab592d13c396b60c818cfc65ff2528e206e7a40a180e210"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "60511ad5628ed8e45a552de171c3330bdcdbd5f86f7047e26b505b7a8c824a47"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "18dfe8ada0af83eb86d4b8ff8e202479b7c2ab1ee1f894d9bb07cda1744e8981"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "e25c97f72666319efdd79eafc22301376446912cbb8ac14339c428c98e3ce1b5"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "f759c09a8fef97038be0c9daaee09e5252a3ddaf56870cabc9af11e5fced97d4"
metafile = true

[[files]]
file = "mods/yungs-cave-biomes.pw.toml"
hash = "1b458a12e9c076ae870dfaa64aaede89c7e6d18fe0c915d89b349a0af4250253"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "743e4ac214adfb6d757f50987cbdcb449bf92d075bcebf7f7a739d8cd1d2e2f1"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "4bcf74d4569def60ca031d565350952c2edcc420f26278bc7997654a77b6fb4d"
metafile = true
